---
- name: check yay installed
  stat:
    path: /usr/bin/yay
  register: yay_installed_stat

- name: package.yaml
  include_tasks: package.yaml
  when: yay_installed_stat.stat.exists == False

- name: update and upgrade
  shell: yes | yay -Syu
  become: no
