---
# - hosts: master
#   roles:
#     - role: gangut-config
    # - role: vagrant
    # - role: lxd

# - hosts: dnsserver
#   roles:
#     - role: dnsmasq

- hosts: vpnserver
  roles:
    - role: "softether-arch"
