---
- name: check yay installed
  stat:
    path: /usr/bin/vpnserver
  register: vpnserver_installed_stat

- name: install softether
  shell: yes | yay -S softethervpn
  become: no
  when: vpnserver_installed_stat.stat.exists == False
