---
- name: init
  shell: lxd init --auto

# promiscast on にしなくても使えた
# - name: promisc on

- name: "sysctl ipv4 forward on"
  copy:
    src: sysctl.conf
    dest: /etc/sysctl.conf
    backup: yes

- name: "mkdir {{ lxd_prof_dir }}"
  file:
    path: "{{ lxd_prof_dir }}"
    state: directory

- name: "locate macvlan profile"
  template:
    src: mvlprof.profile.j2
    dest: "{{ lxd_prof_dir }}/mvlprof.profile"

- name: "import macvlanprofile"
  shell: lxc profile create mvlprof && cat {{ lxd_prof_dir }}/mvlprof.profile | lxc profile edit mvlprof
# "Error: Error inserting \"mvlprof\" into database: The profile already exists"
  ignore_errors: yes

- name: "ensure existing user-crontab file"
  file:
    path: "{{ crontab_dir }}/{{ ansible_user }}"
    state: touch

- name: "check lxd is running per boot by cron"
  blockinfile:
    block: |
      @reboot lxc list &>/dev/null
    path: "{{ crontab_dir }}/{{ ansible_user }}"
    backup: yes

# - name: "locate lxc build scripts"
#   copy:
#     src: lxcs
#     dest: "{{ lxd_prof_dir }}"

# - name: "locate lxc memo"
#   copy:
#     src: dirty_memo.txt
#     dest: "{{ lxd_prof_dir }}/dirty_memo.txt"
