---
localdomain: myhome.localnet

dnsmasq_msg: |
  To regist DomainName,
  white down to /etc/hosts

ip_dn_list: |
  192.168.12.50 tashkent.{{ localdomain }}
  192.168.12.60 gangut.{{ localdomain }}
  192.168.12.70 verniy.{{ localdomain }}
  192.168.12.160 vagrant-dnsmasq.{{ localdomain }}

  192.168.12.131 vagrant-akatsuki.{{ localdomain }}
  192.168.12.132 vagrant-hibiki.{{ localdomain }}
  192.168.12.133 vagrant-ikazuchi.{{ localdomain }}
  192.168.12.134 vagrant-inazuma.{{ localdomain }}


dnsmasq_resolvconf_path: "/etc/resolv-dnsmasq.conf"

nameserver_primary: "1.1.1.1"
nameserver_secondary: "1.0.0.1"
