---
- name: "template dnsmasq.conf"
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    backup: yes

- name: "template resolv-dnsmasq.conf"
  template:
    src: resolv-dnsmasq.conf.j2
    dest: "{{ dnsmasq_resolvconf_path }}"
    backup: yes

- name: "re-link resolv.conf"
  file:
    state: link
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf

- name: "stop systemd-resolved"
  systemd:
    name: systemd-resolved.service
    state: stopped
    enabled: no

- name: "add domain names to /etc/hosts"
  blockinfile:
    path: /etc/hosts
    insertbefore: "# The following lines are desirable for IPv6 capable hosts"
    marker: "### {mark} Domain names (used by dnsmasq) ###"
    block: "{{ ip_dn_list }}"
    backup: yes

- name: "notify message"
  shell: ":"
  notify: dnsmasq_message
