---
- name: template wg0.conf
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    mode: '0600'

- name: allow ipv4 forwarding
  lineinfile:
    path: /etc/sysctl.d/99-sysctl.conf
    line: net.ipv4.ip_forward = 1
    create: yes
  notify: loadsysctl

